_wandb:
    value:
        cli_version: 0.22.0
        e:
            ggx1ts5pfoyi8gw54kw6eakb24mz855a:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "3221225472"
                codePath: Trees/ModelCreationV2.ipynb
                codePathLocal: ModelCreationV2.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "186242064384"
                email: iiro23001@student.hamk.fi
                executable: /opt/anaconda3/envs/SolutionsInPR/bin/python
                git:
                    commit: 35895727c83616b9eb5609ca3d42a422ecc760c0
                    remote: https://github.com/RasmusLaitilaHAMK/ArtificialIntelligence_projects.git
                host: Iiro-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/iirokaki/Opiskelu Syksy 2025/artificial_int_2025/GitHub/ArtificialIntelligence_projects/Trees/ModelCreationV2.ipynb
                python: CPython 3.12.3
                root: /Users/iirokaki/Opiskelu Syksy 2025/artificial_int_2025/GitHub/ArtificialIntelligence_projects/Trees
                startedAt: "2025-10-21T08:03:49.549168Z"
                writerId: ggx1ts5pfoyi8gw54kw6eakb24mz855a
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 105
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.12.3
            "5": 0.22.0
            "8":
                - 1
            "12": 0.22.0
            "13": darwin-arm64
architecture:
    value: ResNet18
batch_size:
    value: 16
dataset:
    value: RPS
epochs:
    value: 15
image_size:
    value: 224
learning_rate:
    value: 0.001
